// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hr_service.grpc.pb.job;

public interface GetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
