// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hr_service.grpc.pb.job;

public final class Job {
  private Job() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tjob.proto\"b\n\013JobResponse\022\014\n\004name\030\001 \001(\t" +
      "\022\022\n\nexperience\030\002 \001(\005\022\016\n\006skills\030\003 \003(\t\022\023\n\013" +
      "description\030\004 \001(\t\022\014\n\004city\030\005 \001(\t\"\017\n\rGetAl" +
      "lRequest\",\n\016GetAllResponse\022\032\n\004jobs\030\001 \003(\013" +
      "2\014.JobResponse27\n\nJobService\022)\n\006GetAll\022\016" +
      ".GetAllRequest\032\017.GetAllResponseB\"\n\036ru.it" +
      "is.hr_service.grpc.pb.jobP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_JobResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JobResponse_descriptor,
        new java.lang.String[] { "Name", "Experience", "Skills", "Description", "City", });
    internal_static_GetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllResponse_descriptor,
        new java.lang.String[] { "Jobs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
