// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: job.proto

package ru.itis.hr_service.grpc.pb.job;

public interface JobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 experience = 2;</code>
   * @return The experience.
   */
  int getExperience();

  /**
   * <code>repeated string skills = 3;</code>
   * @return A list containing the skills.
   */
  java.util.List<java.lang.String>
      getSkillsList();
  /**
   * <code>repeated string skills = 3;</code>
   * @return The count of skills.
   */
  int getSkillsCount();
  /**
   * <code>repeated string skills = 3;</code>
   * @param index The index of the element to return.
   * @return The skills at the given index.
   */
  java.lang.String getSkills(int index);
  /**
   * <code>repeated string skills = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the skills at the given index.
   */
  com.google.protobuf.ByteString
      getSkillsBytes(int index);

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string city = 5;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 5;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
