// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hr_service.grpc.pb.cv;

public final class Cv {
  private Cv() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CVResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010cv.proto\"c\n\nCVResponse\022\021\n\tfirstName\030\001 " +
      "\001(\t\022\020\n\010lastName\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\022\022\n\ne" +
      "xperience\030\004 \001(\005\022\016\n\006skills\030\005 \003(\t\"\017\n\rGetAl" +
      "lRequest\"*\n\016GetAllResponse\022\030\n\003cvs\030\001 \003(\0132" +
      "\013.CVResponse26\n\tCVService\022)\n\006GetAll\022\016.Ge" +
      "tAllRequest\032\017.GetAllResponseB!\n\035ru.itis." +
      "hr_service.grpc.pb.cvP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CVResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CVResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CVResponse_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "City", "Experience", "Skills", });
    internal_static_GetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllResponse_descriptor,
        new java.lang.String[] { "Cvs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
