// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hr_service.grpc.pb.cv;

public interface CVResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CVResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string city = 3;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 3;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>int32 experience = 4;</code>
   * @return The experience.
   */
  int getExperience();

  /**
   * <code>repeated string skills = 5;</code>
   * @return A list containing the skills.
   */
  java.util.List<java.lang.String>
      getSkillsList();
  /**
   * <code>repeated string skills = 5;</code>
   * @return The count of skills.
   */
  int getSkillsCount();
  /**
   * <code>repeated string skills = 5;</code>
   * @param index The index of the element to return.
   * @return The skills at the given index.
   */
  java.lang.String getSkills(int index);
  /**
   * <code>repeated string skills = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the skills at the given index.
   */
  com.google.protobuf.ByteString
      getSkillsBytes(int index);
}
