// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hr_service.grpc.pb.cv;

public interface GetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  java.util.List<ru.itis.hr_service.grpc.pb.cv.CVResponse> 
      getCvsList();
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  ru.itis.hr_service.grpc.pb.cv.CVResponse getCvs(int index);
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  int getCvsCount();
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  java.util.List<? extends ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder> 
      getCvsOrBuilderList();
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder getCvsOrBuilder(
      int index);
}
