// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cv.proto

package ru.itis.hr_service.grpc.pb.cv;

/**
 * Protobuf type {@code GetAllResponse}
 */
public final class GetAllResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetAllResponse)
    GetAllResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllResponse.newBuilder() to construct.
  private GetAllResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllResponse() {
    cvs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.itis.hr_service.grpc.pb.cv.Cv.internal_static_GetAllResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.itis.hr_service.grpc.pb.cv.Cv.internal_static_GetAllResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.itis.hr_service.grpc.pb.cv.GetAllResponse.class, ru.itis.hr_service.grpc.pb.cv.GetAllResponse.Builder.class);
  }

  public static final int CVS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<ru.itis.hr_service.grpc.pb.cv.CVResponse> cvs_;
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ru.itis.hr_service.grpc.pb.cv.CVResponse> getCvsList() {
    return cvs_;
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder> 
      getCvsOrBuilderList() {
    return cvs_;
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public int getCvsCount() {
    return cvs_.size();
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public ru.itis.hr_service.grpc.pb.cv.CVResponse getCvs(int index) {
    return cvs_.get(index);
  }
  /**
   * <code>repeated .CVResponse cvs = 1;</code>
   */
  @java.lang.Override
  public ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder getCvsOrBuilder(
      int index) {
    return cvs_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cvs_.size(); i++) {
      output.writeMessage(1, cvs_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cvs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cvs_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.itis.hr_service.grpc.pb.cv.GetAllResponse)) {
      return super.equals(obj);
    }
    ru.itis.hr_service.grpc.pb.cv.GetAllResponse other = (ru.itis.hr_service.grpc.pb.cv.GetAllResponse) obj;

    if (!getCvsList()
        .equals(other.getCvsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCvsCount() > 0) {
      hash = (37 * hash) + CVS_FIELD_NUMBER;
      hash = (53 * hash) + getCvsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.itis.hr_service.grpc.pb.cv.GetAllResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetAllResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetAllResponse)
      ru.itis.hr_service.grpc.pb.cv.GetAllResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.itis.hr_service.grpc.pb.cv.Cv.internal_static_GetAllResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.itis.hr_service.grpc.pb.cv.Cv.internal_static_GetAllResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.itis.hr_service.grpc.pb.cv.GetAllResponse.class, ru.itis.hr_service.grpc.pb.cv.GetAllResponse.Builder.class);
    }

    // Construct using ru.itis.hr_service.grpc.pb.cv.GetAllResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (cvsBuilder_ == null) {
        cvs_ = java.util.Collections.emptyList();
      } else {
        cvs_ = null;
        cvsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.itis.hr_service.grpc.pb.cv.Cv.internal_static_GetAllResponse_descriptor;
    }

    @java.lang.Override
    public ru.itis.hr_service.grpc.pb.cv.GetAllResponse getDefaultInstanceForType() {
      return ru.itis.hr_service.grpc.pb.cv.GetAllResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ru.itis.hr_service.grpc.pb.cv.GetAllResponse build() {
      ru.itis.hr_service.grpc.pb.cv.GetAllResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.itis.hr_service.grpc.pb.cv.GetAllResponse buildPartial() {
      ru.itis.hr_service.grpc.pb.cv.GetAllResponse result = new ru.itis.hr_service.grpc.pb.cv.GetAllResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ru.itis.hr_service.grpc.pb.cv.GetAllResponse result) {
      if (cvsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cvs_ = java.util.Collections.unmodifiableList(cvs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cvs_ = cvs_;
      } else {
        result.cvs_ = cvsBuilder_.build();
      }
    }

    private void buildPartial0(ru.itis.hr_service.grpc.pb.cv.GetAllResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.itis.hr_service.grpc.pb.cv.GetAllResponse) {
        return mergeFrom((ru.itis.hr_service.grpc.pb.cv.GetAllResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.itis.hr_service.grpc.pb.cv.GetAllResponse other) {
      if (other == ru.itis.hr_service.grpc.pb.cv.GetAllResponse.getDefaultInstance()) return this;
      if (cvsBuilder_ == null) {
        if (!other.cvs_.isEmpty()) {
          if (cvs_.isEmpty()) {
            cvs_ = other.cvs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCvsIsMutable();
            cvs_.addAll(other.cvs_);
          }
          onChanged();
        }
      } else {
        if (!other.cvs_.isEmpty()) {
          if (cvsBuilder_.isEmpty()) {
            cvsBuilder_.dispose();
            cvsBuilder_ = null;
            cvs_ = other.cvs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cvsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCvsFieldBuilder() : null;
          } else {
            cvsBuilder_.addAllMessages(other.cvs_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ru.itis.hr_service.grpc.pb.cv.CVResponse m =
                  input.readMessage(
                      ru.itis.hr_service.grpc.pb.cv.CVResponse.parser(),
                      extensionRegistry);
              if (cvsBuilder_ == null) {
                ensureCvsIsMutable();
                cvs_.add(m);
              } else {
                cvsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ru.itis.hr_service.grpc.pb.cv.CVResponse> cvs_ =
      java.util.Collections.emptyList();
    private void ensureCvsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cvs_ = new java.util.ArrayList<ru.itis.hr_service.grpc.pb.cv.CVResponse>(cvs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itis.hr_service.grpc.pb.cv.CVResponse, ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder, ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder> cvsBuilder_;

    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public java.util.List<ru.itis.hr_service.grpc.pb.cv.CVResponse> getCvsList() {
      if (cvsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cvs_);
      } else {
        return cvsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public int getCvsCount() {
      if (cvsBuilder_ == null) {
        return cvs_.size();
      } else {
        return cvsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public ru.itis.hr_service.grpc.pb.cv.CVResponse getCvs(int index) {
      if (cvsBuilder_ == null) {
        return cvs_.get(index);
      } else {
        return cvsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder setCvs(
        int index, ru.itis.hr_service.grpc.pb.cv.CVResponse value) {
      if (cvsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCvsIsMutable();
        cvs_.set(index, value);
        onChanged();
      } else {
        cvsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder setCvs(
        int index, ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder builderForValue) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.set(index, builderForValue.build());
        onChanged();
      } else {
        cvsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(ru.itis.hr_service.grpc.pb.cv.CVResponse value) {
      if (cvsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCvsIsMutable();
        cvs_.add(value);
        onChanged();
      } else {
        cvsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(
        int index, ru.itis.hr_service.grpc.pb.cv.CVResponse value) {
      if (cvsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCvsIsMutable();
        cvs_.add(index, value);
        onChanged();
      } else {
        cvsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(
        ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder builderForValue) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.add(builderForValue.build());
        onChanged();
      } else {
        cvsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addCvs(
        int index, ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder builderForValue) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.add(index, builderForValue.build());
        onChanged();
      } else {
        cvsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder addAllCvs(
        java.lang.Iterable<? extends ru.itis.hr_service.grpc.pb.cv.CVResponse> values) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cvs_);
        onChanged();
      } else {
        cvsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder clearCvs() {
      if (cvsBuilder_ == null) {
        cvs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cvsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public Builder removeCvs(int index) {
      if (cvsBuilder_ == null) {
        ensureCvsIsMutable();
        cvs_.remove(index);
        onChanged();
      } else {
        cvsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder getCvsBuilder(
        int index) {
      return getCvsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder getCvsOrBuilder(
        int index) {
      if (cvsBuilder_ == null) {
        return cvs_.get(index);  } else {
        return cvsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public java.util.List<? extends ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder> 
         getCvsOrBuilderList() {
      if (cvsBuilder_ != null) {
        return cvsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cvs_);
      }
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder addCvsBuilder() {
      return getCvsFieldBuilder().addBuilder(
          ru.itis.hr_service.grpc.pb.cv.CVResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder addCvsBuilder(
        int index) {
      return getCvsFieldBuilder().addBuilder(
          index, ru.itis.hr_service.grpc.pb.cv.CVResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .CVResponse cvs = 1;</code>
     */
    public java.util.List<ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder> 
         getCvsBuilderList() {
      return getCvsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ru.itis.hr_service.grpc.pb.cv.CVResponse, ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder, ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder> 
        getCvsFieldBuilder() {
      if (cvsBuilder_ == null) {
        cvsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ru.itis.hr_service.grpc.pb.cv.CVResponse, ru.itis.hr_service.grpc.pb.cv.CVResponse.Builder, ru.itis.hr_service.grpc.pb.cv.CVResponseOrBuilder>(
                cvs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cvs_ = null;
      }
      return cvsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetAllResponse)
  }

  // @@protoc_insertion_point(class_scope:GetAllResponse)
  private static final ru.itis.hr_service.grpc.pb.cv.GetAllResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.itis.hr_service.grpc.pb.cv.GetAllResponse();
  }

  public static ru.itis.hr_service.grpc.pb.cv.GetAllResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllResponse>() {
    @java.lang.Override
    public GetAllResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.itis.hr_service.grpc.pb.cv.GetAllResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

